---
include:
  - project: 'core/ci-config'
    ref: master
    file: 'config/common/master.yml'
  - project: 'core/ci-config'
    ref: master
    file: 'jobs/common/master.yml'

before_script:
  - . /duneci/bin/duneci-init-job
  - duneci-install-module https://gitlab.dune-project.org/core/dune-common.git
  - duneci-install-module https://gitlab.dune-project.org/core/dune-geometry.git

debian-11-gcc-9-17-python:
  image: registry.dune-project.org/docker/ci/debian:11
  script: duneci-standard-test
  stage: test
  variables:
    DUNECI_TOOLCHAIN:  gcc-9-17
    # the CMAKE_FLAGS used to build the modules - set python bindings to on
    # Note: DUNE_RUNNING_IN_CI only needed unti ci image updating fixed on gitlab
    DUNECI_CMAKE_FLAGS: '-DDUNE_RUNNING_IN_CI=TRUE -DDUNE_ENABLE_PYTHONBINDINGS=ON -DALLOW_CXXFLAGS_OVERWRITE=ON'
    # add some logging output from the python bindings
    DUNE_LOG_LEVEL:     DEBUG
  tags: [duneci]
ubuntu-20.04-clang-10-20-python:
  image: registry.dune-project.org/docker/ci/ubuntu:20.04
  script: duneci-standard-test
  stage: test
  variables:
    DUNECI_TOOLCHAIN: clang-10-20
    # the CMAKE_FLAGS used to build the modules - set python bindings to on
    # Note: DUNE_RUNNING_IN_CI only needed unti ci image updating fixed on gitlab
    DUNECI_CMAKE_FLAGS: '-DDUNE_RUNNING_IN_CI=TRUE -DDUNE_ENABLE_PYTHONBINDINGS=ON -DALLOW_CXXFLAGS_OVERWRITE=ON'
    # add some logging output from the python bindings
    DUNE_LOG_LEVEL:     DEBUG
  tags: [duneci]
